In [29]:
# Import and Print the numpy version and the configuration (★☆☆)
import numpy as np
np.version.version

'1.24.3'

In [5]:
# 2. Create a null vector of size 10 (★☆☆)
ten_zero = np.zeros(10)
print(ten_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
# How to find the memory size of any array (★☆☆)
np.size(ten_zero)

10

In [9]:
# Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
ten_zero[5] = 1
print(ten_zero)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [12]:
#Create a vector with values ranging from 10 to 49 (★☆☆)
first_r = np.arange(10, 50)
print(first_r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
# Reverse a vector (first element becomes last) (★☆☆)
revert_first_r = np.flip(first_r) # first_r[::-1]
print(revert_first_r)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
# Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
twoD = np.arange(9).reshape(3, 3)
print(twoD)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
# Find indices of non-zero elements from [1,2,0,0,4,0,5,7,0,0,23,67,0,0,0] (★☆☆)
my_indices = np.where(~np.isin([1,2,0,0,4,0,5,7,0,0,23,67,0,0,0], 0))
print(my_indices)

(array([ 0,  1,  4,  6,  7, 10, 11], dtype=int64),)


In [20]:
#Create a 5x5 identity matrix (★☆☆)
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
# Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
ten_ten = np.random.randint(0, 200, size=(10, 10))
print(ten_ten)
max_ten_ten = np.max(ten_ten)
min_ten_ten = np.min(ten_ten)
print(min_ten_ten, max_ten_ten)

[[  3 123 176 142  92 191 154  98 193 143]
 [ 69 107  67 147 128  77 198  46  87  31]
 [  7  21 170  27  58   3 178 111  53   4]
 [147  95  76 137 182 102  20   0  12  70]
 [145  27  92 176 137  57 183 113  41 107]
 [ 44  47  11  52 138 115  41 133 103 155]
 [142 170  47  68 127 114 191 168 189  32]
 [ 54 157  50  49 124 127  15 132 137 122]
 [123 127 149  56  51 172 196  56 156 199]
 [114 146 185 199 169 104 140 157 182 170]]
0 199


In [26]:
# Create a random vector of size 30 and find the mean value (★☆☆)
my_arr= np.random.randint(1, 500, size=(30))
mean_of_my_arr = np.mean(my_arr)
print(mean_of_my_arr)

211.56666666666666


In [28]:
# Create a 2d array with 1 on the border and 0 inside (★☆☆)
my_arr1 = np.zeros((6, 6))
my_arr1[0, :] = 1   #top
my_arr1[-1, :] = 1  #bottom
my_arr1[:, -1] = 1  #right
my_arr1[:, 0] = 1   #left
print(my_arr1)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [33]:
# How to add a border (filled with 0's) around an existing array?
z = np.ones((6, 6))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
# What is the result of the following expression? (★☆☆)
# 0 * np.nan  --> nan
# np.nan == np.nan ---> false
# np.inf > np.nan ---> false
# np.nan - np.nan ---> nan
# np.nan in set([np.nan]) ---> true
# 0.3 == 3 * 0.1  ---> false ---> np.isclose(0.3, 3 * 0.1)

In [42]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
diag_arr = np.diag([1,2,3,4], k=-1)
print(diag_arr)

'''x = np.arange(9).reshape((3, 3))
print(x)
print(np.diag(x)) # Output: array([0, 4, 8])
print(np.diag(x, k=1)) # Output: array([1, 5])
print(np.diag(x, k=-1)) # Output: array([3, 7])
print(np.diag(np.diag(x))) # Output: array([[0, 0, 0], [0, 4, 0], [0, 0, 8]])'''

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


'x = np.arange(9).reshape((3, 3))\nprint(x)\nprint(np.diag(x)) # Output: array([0, 4, 8])\nprint(np.diag(x, k=1)) # Output: array([1, 5])\nprint(np.diag(x, k=-1)) # Output: array([3, 7])\nprint(np.diag(np.diag(x))) # Output: array([[0, 0, 0], [0, 4, 0], [0, 0, 8]])'

In [45]:
# Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
x = np.zeros((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [49]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
x = np.arange(336)
x= x.reshape(6, 7, 8)
index = np.unravel_index(100, x.shape)
print("Index:", index)


Index: (1, 5, 4)


In [51]:
#  Create a checkerboard 8x8 matrix using the tile function (★☆☆)
pattern = np.array([[0,1], [0,1]])
x = np.tile(pattern, (4, 4))
print(x)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [54]:
# Normalize a 5x5 random matrix (★☆☆)
matrix = np.random.rand(5, 5)
row_sums = matrix.sum(axis=1, keepdims=True)
normalized_matrix = matrix / row_sums

print("Original Matrix:\n", matrix)
print("Row-wise Normalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.95459333 0.17724759 0.60898657 0.6528512  0.69480921]
 [0.62029426 0.94503574 0.24052847 0.58489452 0.24830536]
 [0.32393689 0.45456209 0.34359224 0.74736416 0.85882568]
 [0.04440224 0.65623418 0.81076896 0.41842548 0.62490833]
 [0.4779913  0.98334726 0.540346   0.680155   0.88457145]]
Row-wise Normalized Matrix:
 [[0.30908113 0.05738976 0.19717952 0.21138215 0.22496744]
 [0.23504378 0.35809581 0.09114178 0.22163    0.09408862]
 [0.11873296 0.16661117 0.12593726 0.27393225 0.31478637]
 [0.01738034 0.25686934 0.3173588  0.16378403 0.24460749]
 [0.13402586 0.2757246  0.15150974 0.19071133 0.24802847]]


In [55]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
rgba_dtype = np.dtype([
    ('r', np.uint8),  # Red channel
    ('g', np.uint8),  # Green channel
    ('b', np.uint8),  # Blue channel
    ('a', np.uint8)   # Alpha channel
])


colors = np.array([(255, 0, 132, 255), (0, 234, 0, 255), (0, 0, 255, 179)], dtype=rgba_dtype)

# Print the array
print(colors)

[(255,   0, 132, 255) (  0, 234,   0, 255) (  0,   0, 255, 179)]


In [58]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
x = np.random.randint(15, size=(5, 3))
y = np.random.randint(15, size=(3, 2))
result = x @ y
print(result)

[[106 164]
 [109 154]
 [187 258]
 [ 84 216]
 [173 176]]


In [61]:
# Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
x = np.random.randint(50, size=20)
print(x)
x[3:9:] *= -1
print(x)

[10 29 42 32 35 45  6 10 28 48  9 28 10 34 27 31 12 15 14  2]
[ 10  29  42 -32 -35 -45  -6 -10 -28  48   9  28  10  34  27  31  12  15
  14   2]


In [62]:
# Consider an integer vector Z, which of these expressions are legal? (★☆☆)
# Z**Z legal
# 2 << Z >> 2  legal
# Z <- Z nicht legal
# 1j*Z   legal
# Z/1/1  legal
# Z<Z>Z  legal

In [63]:
# How to round away from zero a float array ? (★☆☆)
arr = np.array([-1.5, -2.3, 0.2, 1.7, 2.5])
rounded = np.copysign(np.ceil(np.abs(arr)), arr)
print(rounded)

[-2. -3.  1.  2.  3.]


In [66]:
# How to find common values between two arrays? (★☆☆)
array1 = np.array([1, 4, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 4])
common_values = np.intersect1d(array1, array2)
print("Common values:", common_values)

Common values: [4 5]


In [69]:
# How to get the dates of yesterday, today and tomorrow? (★☆☆)
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-07-12
Today: 2025-07-13
Tomorrow: 2025-07-14
