In [1]:
# Import and Print the numpy version and the configuration (★☆☆)
import numpy as np
np.version.version

'1.24.3'

In [2]:
# 2. Create a null vector of size 10 (★☆☆)
ten_zero = np.zeros(10)
print(ten_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# How to find the memory size of any array (★☆☆)
np.size(ten_zero)

10

In [4]:
# Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
ten_zero[5] = 1
print(ten_zero)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [5]:
#Create a vector with values ranging from 10 to 49 (★☆☆)
first_r = np.arange(10, 50)
print(first_r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
# Reverse a vector (first element becomes last) (★☆☆)
revert_first_r = np.flip(first_r) # first_r[::-1]
print(revert_first_r)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [7]:
# Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
twoD = np.arange(9).reshape(3, 3)
print(twoD)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Find indices of non-zero elements from [1,2,0,0,4,0,5,7,0,0,23,67,0,0,0] (★☆☆)
my_indices = np.where(~np.isin([1,2,0,0,4,0,5,7,0,0,23,67,0,0,0], 0))
print(my_indices)

(array([ 0,  1,  4,  6,  7, 10, 11], dtype=int64),)


In [9]:
#Create a 5x5 identity matrix (★☆☆)
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
# Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
ten_ten = np.random.randint(0, 200, size=(10, 10))
print(ten_ten)
max_ten_ten = np.max(ten_ten)
min_ten_ten = np.min(ten_ten)
print(min_ten_ten, max_ten_ten)

[[182  48 113  62 169  21  36 116 162 130]
 [115 188  89 154 164 162  27  32 192  35]
 [ 18 159  19  34 151 118 178 135   9 170]
 [125 138 133 170 109  42  95 166  30 137]
 [103 191 186  27 120 122  67  71 189 152]
 [124 168  66 107  17 166 139  17 166 155]
 [ 92  81 127 151  91 120  60 123  98  29]
 [ 13  61 198  68 112 176  28 176 109 143]
 [ 10  81 128  78 161 130 191 173  10 174]
 [191  87 150 121   3 187  34 105 150  61]]
3 198


In [11]:
# Create a random vector of size 30 and find the mean value (★☆☆)
my_arr= np.random.randint(1, 500, size=(30))
mean_of_my_arr = np.mean(my_arr)
print(mean_of_my_arr)

260.43333333333334


In [12]:
# Create a 2d array with 1 on the border and 0 inside (★☆☆)
my_arr1 = np.zeros((6, 6))
my_arr1[0, :] = 1   #top
my_arr1[-1, :] = 1  #bottom
my_arr1[:, -1] = 1  #right
my_arr1[:, 0] = 1   #left
print(my_arr1)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [13]:
# How to add a border (filled with 0's) around an existing array?
z = np.ones((6, 6))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
# What is the result of the following expression? (★☆☆)
# 0 * np.nan  --> nan
# np.nan == np.nan ---> false
# np.inf > np.nan ---> false
# np.nan - np.nan ---> nan
# np.nan in set([np.nan]) ---> true
# 0.3 == 3 * 0.1  ---> false ---> np.isclose(0.3, 3 * 0.1)

In [15]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
diag_arr = np.diag([1,2,3,4], k=-1)
print(diag_arr)

'''x = np.arange(9).reshape((3, 3))
print(x)
print(np.diag(x)) # Output: array([0, 4, 8])
print(np.diag(x, k=1)) # Output: array([1, 5])
print(np.diag(x, k=-1)) # Output: array([3, 7])
print(np.diag(np.diag(x))) # Output: array([[0, 0, 0], [0, 4, 0], [0, 0, 8]])'''

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


'x = np.arange(9).reshape((3, 3))\nprint(x)\nprint(np.diag(x)) # Output: array([0, 4, 8])\nprint(np.diag(x, k=1)) # Output: array([1, 5])\nprint(np.diag(x, k=-1)) # Output: array([3, 7])\nprint(np.diag(np.diag(x))) # Output: array([[0, 0, 0], [0, 4, 0], [0, 0, 8]])'

In [16]:
# Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
x = np.zeros((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [17]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
x = np.arange(336)
x= x.reshape(6, 7, 8)
index = np.unravel_index(100, x.shape)
print("Index:", index)


Index: (1, 5, 4)


In [18]:
#  Create a checkerboard 8x8 matrix using the tile function (★☆☆)
pattern = np.array([[0,1], [0,1]])
x = np.tile(pattern, (4, 4))
print(x)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [19]:
# Normalize a 5x5 random matrix (★☆☆)
matrix = np.random.rand(5, 5)
row_sums = matrix.sum(axis=1, keepdims=True)
normalized_matrix = matrix / row_sums

print("Original Matrix:\n", matrix)
print("Row-wise Normalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.80479384 0.33121928 0.99108744 0.68885426 0.24470219]
 [0.26820328 0.05776265 0.14059187 0.47137629 0.10702865]
 [0.19334876 0.56721498 0.69077276 0.24415798 0.41907842]
 [0.22883991 0.51848744 0.74853097 0.52071915 0.03097708]
 [0.90981998 0.21730302 0.24789336 0.17521525 0.72459911]]
Row-wise Normalized Matrix:
 [[0.26294806 0.10821836 0.32381526 0.22506745 0.07995087]
 [0.25666301 0.05527724 0.13454247 0.45109387 0.10242341]
 [0.09143632 0.26824092 0.32667247 0.11546444 0.19818585]
 [0.11176255 0.25322277 0.36557315 0.25431271 0.01512882]
 [0.39995063 0.09552492 0.10897222 0.07702342 0.31852881]]


In [20]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
rgba_dtype = np.dtype([
    ('r', np.uint8),  # Red channel
    ('g', np.uint8),  # Green channel
    ('b', np.uint8),  # Blue channel
    ('a', np.uint8)   # Alpha channel
])


colors = np.array([(255, 0, 132, 255), (0, 234, 0, 255), (0, 0, 255, 179)], dtype=rgba_dtype)

# Print the array
print(colors)

[(255,   0, 132, 255) (  0, 234,   0, 255) (  0,   0, 255, 179)]


In [21]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
x = np.random.randint(15, size=(5, 3))
y = np.random.randint(15, size=(3, 2))
result = x @ y
print(result)

[[259 184]
 [ 74  36]
 [255 176]
 [399 264]
 [393 246]]


In [22]:
# Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
x = np.random.randint(50, size=20)
print(x)
x[3:9:] *= -1
print(x)

[14  2  4 23 11 32 12 14 25 40 43 31  0 33 26 12  6 14 14 21]
[ 14   2   4 -23 -11 -32 -12 -14 -25  40  43  31   0  33  26  12   6  14
  14  21]


In [23]:
# Consider an integer vector Z, which of these expressions are legal? (★☆☆)
# Z**Z legal
# 2 << Z >> 2  legal
# Z <- Z nicht legal
# 1j*Z   legal
# Z/1/1  legal
# Z<Z>Z  legal

In [24]:
# How to round away from zero a float array ? (★☆☆)
arr = np.array([-1.5, -2.3, 0.2, 1.7, 2.5])
rounded = np.copysign(np.ceil(np.abs(arr)), arr)
print(rounded)

[-2. -3.  1.  2.  3.]


In [25]:
# How to find common values between two arrays? (★☆☆)
array1 = np.array([1, 4, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 4])
common_values = np.intersect1d(array1, array2)
print("Common values:", common_values)

Common values: [4 5]


In [26]:
# How to get the dates of yesterday, today and tomorrow? (★☆☆)
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-07-19
Today: 2025-07-20
Tomorrow: 2025-07-21


In [28]:
#How to get all the dates corresponding to the month of July 2016? (★★☆)
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

july = np.arange(start_date, end_date, dtype='datetime64[D]')
print(july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [32]:
# Extract the integer part of a random array of positive numbers using 3 different methods (★★☆)
random_nums = np.random.rand(10) * 50
print(random_nums)
#Method 1
integer_part = random_nums -(random_nums % 1)
print(integer_part)
# Method 2
integer_part1 = np.floor(random_nums)
print(integer_part1)
# Method 3
use_astype = random_nums.astype(int)
print(use_astype)

[45.88340987 10.2962749  29.14617735 48.33591434 18.25349388 39.06424233
 19.56698059  6.63911339 20.18575736 33.10399923]
[45. 10. 29. 48. 18. 39. 19.  6. 20. 33.]
[45. 10. 29. 48. 18. 39. 19.  6. 20. 33.]
[45 10 29 48 18 39 19  6 20 33]


In [36]:
# Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
matrix = np.tile(np.arange(5), (5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [39]:
#Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
#`hint: np.fromiter`
arr = np.fromiter(range(10), dtype=int)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
arr = np.random.rand(10)
arr

array([0.07612696, 0.34493126, 0.9046653 , 0.55206365, 0.19544641,
       0.75580842, 0.06936476, 0.6178229 , 0.41797937, 0.06578582])

In [42]:
# Create a random vector of size 10 and sort it (★★☆)
arr = np.random.rand(10) * 100
arr = np.sort(arr)
arr

array([10.63483484, 12.30055496, 25.03094159, 43.89056885, 69.80282197,
       73.13307065, 73.66725427, 87.65906895, 89.10658387, 89.12879344])

In [43]:
# How to sum a small array faster than np.sum? (★★☆)
result = np.add.reduce(arr)
result

574.3544933811013